### ISSUE TITLE
configure API_URL_DOCKER on linux (host.docker.internal)

### ISSUE THREAD

**Issue by devthejo** [SocialGouv/emjpm#2322]
**Describe the bug**
en utilisant l'exemple de variable API_URL_DOCKER host.docker.internal présent dans .env.sample, j'obtiens
```
Error fetching JWK: ConnectionFailure Network.Socket.getAddrInfo (called with preferred socket type/protocol: AddrInfo {addrFlags = [AI_ADDRCONFIG], addrFamily = AF_UNSPEC, addrSocketType = Stream, addrProtocol = 0, addrAddress = <assumed to be undefined>, addrCanonName = <assumed to be undefined>}, host name: Just "host.docker.internal", service name: Just "4000"): does not exist (Name or service not known)
```

**To Reproduce**
1. Install Linux Mint on your laptop (la meilleur distro linux de bureau, soit dit en passant ;-))
2. git clone git@github.com:SocialGouv/emjpm.git && cd emjpm
3. cp .env.sample .env (ou bien utiliser le .env fournis en mp par votre collègue ;-))
4. docker-compose up --build

**Expected behavior**
Que les services montent sans problèmes

**Desktop (please complete the following information):**
 - OS: Linux Mint

"host.docker.internal" semble spécifique à Mac

**Comment by devthejo** [comment]
according to:
https://stackoverflow.com/a/48547074/5338073
just replace `host.docker.internal` by docker default ip `172.17.0.1` in .env file

**Comment by devthejo** [comment]
172.17.0.1 solved problem of API_URL_DOCKER but not for HASURA_WEB_HOOK_BASE_URL that need to access host network if yarn running locally (for jwt), so let's dockerize app in docker-compose

**Comment by devthejo** [comment]
solved by adding to docker-compose.yaml
```yaml
  emjpm:
    image: node:10-alpine
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    ports:
      - 3000:3000
    restart: always
    command: "yarn dev"
```

replacing in .env `host.docker.internal` for  API_URL_DOCKER and HASURA_WEB_HOOK_BASE_URL, by service name: `emjpm`, commit will follow
