### ISSUE TITLE
[secu] network policy

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/emjpm#2715]
We should add a network policy to the deployment

This should be enough : 

```yml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: netpol-emjpm
  namespace: emjpm
spec:
  ingress:
    - from:
        - podSelector: {}
    - from:
        - namespaceSelector:
            matchLabels:
              network-policy/source: ingress-controller
    - from:
        - namespaceSelector:
            matchLabels:
              network-policy/source: monitoring
  podSelector: {}
  policyTypes:
    - Ingress
 ```
